server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://121.37.185.192:3306/vhr?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: zhangling03

mybatis:
  # 映射mapper.xml 指定mapper.xml映射文件的位置
  mapper-locations: classpath:mapper/*.xml
  #  开启陀峰映射
  configuration:
    map-underscore-to-camel-case: true

# sql 日志
logging:
  level:
    com.ling.vhr.mapper: debug

