server:
  port: 8081
spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/vhr?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://121.37.185.192:3306/flowable?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    # p6spy sql 性能监控
    url: jdbc:p6spy:mysql://127.0.0.1:3306/vhr?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
  rabbitmq:
    host: 192.168.191.128
    port: 5672
    username: guest
    password: guest
  redis:
    database: 1
    host: 121.37.185.192
    port: 6379
    password: zhangling03      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）



mybatis:
  # 映射mapper.xml 指定mapper.xml映射文件的位置
  mapper-locations: classpath:mapper/*.xml,classpath:*/mapper/*.xml
  #  开启陀峰映射
  configuration:
    map-underscore-to-camel-case: true
# rocketmq 配置
mq:
  nameSrvServer: 192.168.65.130:9876
  groupId: vhrApplication
  type: apache
#  type: aa

# es 配置
easy-es:
  enable: true #默认为true,若为false则认为不启用本框架
  address : 192.168.65.130:9200 # es的连接地址,必须含端口 若为集群,则可以用逗号隔开 例如:127.0.0.1:9200,127.0.0.2:9200
  username:  #若无 则可省略此行配置
  password:  #若无 则可省略此行配置

# flowable 配置
# 是否在项目启动的时候，自动去检查流程定义目录下是否有对应的流程定义文件，如果这个属性为 true（默认即次），就表示去检查，否则不检查（意味着不会自动部署流程）
#flowable:
#  check-process-definitions: false
#  flowable:
    # 设置流程定义文件的位置，默认位置就是 classpath*:/processes/
#    process-definition-location-prefix: classpath*:/processes/
    # 这个是指定流程定义 XML 文件的后缀，默认后缀有两个：**.bpmn20.xml,**.bpmn
#    process-definition-location-suffixes: **.bpmn20.xml,**.bpmn

# sql 日志
logging:
  level:
    com.ling: debug
    com.ling.vhr.mapper: debug
    org.flowable: info
    org.mybatis.spring.mapper: error

logdir: logs

